version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ighana
      POSTGRES_PASSWORD: ighana_pass
      POSTGRES_DB: ighana_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ighana.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
    command: npm start
    environment:
      DATABASE_URL: postgres://ighana:ighana_pass@postgres:5432/ighana_db
      SESSION_SECRET: supersecretkey
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  pgdata:
  pgadmin_data:
